AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31
  - AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: CodeStar projectId used to associate new resources to team members
  CodeDeployRole:
    Type: String
    Description: IAM role to allow AWS CodeDeploy to manage deployment of AWS Lambda functions
  Stage:
    Type: String
    Description: The name for a project pipeline stage, such as Staging or Prod, for which resources are provisioned and deployed.
    Default: ""
Globals:
  Function:
    AutoPublishAlias: prod
    DeploymentPreference:
      Enabled: true
      Type: AllAtOnce
      Role: !Ref CodeDeployRole
Resources:
  # Definição da Função Lambda.
  GetUserRec:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetUserRec
      Handler: handler.handler
      Runtime: python3.8
      Description: "Função que faz a intermediacao do API Gateway com o SQS"
      MemorySize: 256
      Timeout: 900
      Role: arn:aws:iam::595380434278:role/service-role/LambdaRole        
      Tags:
        teste
      # Environment:
      #   Variables:
      #     DB_USER: xxx
      #     DB_PASSWORD: xxx
      #     DB_HOST: xxx
      #     DB_PORT: xxx
      #     DB_DATABASE: xxx

      # Configuração da VPC para acesso ao RDS
      # VpcConfig:
      #   SecurityGroupIds:
      #     - sg-xxx
      #   SubnetIds:
      #     - subnet-xxx
      #     - subnet-xxx
      #     - subnet-xxx

      # Configuração das Layers utilizadas na Função Lambda
      Layers:
        - !Sub arn:aws:lambda:us-east-1:595380434278:layer:layer_do_patrick:1